Add Json marshaling and unmarshaling
sosodev/duration pull request #3
Opened 2023-09-29 12:01 UTC by arieroos

This should close #2 

I thought it's a good idea. And some contributions to this package will help it's longevity

2023-10-11 02:44 UTC, sosodev requested changes
Thanks for submitting this. Sorry for the slow review. Unfortunately, the tests are failing.

2023-10-11 02:44 UTC, sosodev commented on duration_test.go
> +		t.Errorf("expected: %s, got: %s", `{"d":"P3Y6M4DT12H30M5.5S"}`, string(jsonVal))
This error is hit.

2023-10-11 02:44 UTC, sosodev commented on duration.go
> +func (duration *Duration) MarshalJSON() ([]byte, error) {
Remove the pointer`*` here to fix it.

2023-10-11 07:18 UTC, arieroos commented on duration.go
> +func (duration *Duration) MarshalJSON() ([]byte, error) {
Thanks. I pushed a commit to fix this

2023-10-11 07:20 UTC, arieroos commented
Thanks a million for the review. No need to apologise for taking your time.

I pushed a commit with your suggested fix

2023-10-12 17:35 UTC, sosodev approved these changes

2023-10-12 17:35 UTC, merged

2023-10-12 17:35 UTC, sosodev commented
@arieroos merged. Thanks again for your contribution. 😄